name       : python-docopt
version    : 0.6.2
release    : 4
source     :
    - https://github.com/docopt/docopt/archive/0.6.2.tar.gz : 2113eed1e7fbbcd43fb7ee6a977fb02d0b482753586c9dc1a8e3b7d541426e99
license    : MIT
component  : programming.python
summary    : Pythonic command line arguments parser, that will make you smile.
description: |
    Pythonic command line arguments parser, that will make you smile.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
